### PR TITLE
Adding AML Policy to Disable Public Network Access

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
* Added missing policy to disable public network access for Azure Machine Learning workspaces. This policy is not existing as built-in today and is therefore included here for reference.

### CODE REVIEW

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by marvinbuss** [comment]
Deployment works as expected and effects are also working as shown here:
image

**Comment by amanjeetsingh** [comment]
Did a visual check; compared it to the policies we already have in place; looks ok to me. 
Approving PR.

**Review by amanjeetsingh — APPROVED** [review]
Did a visual check; compared the policy definitions which already work. 
Approving changes. Thanks!

**Pull request merged**
