### PR TITLE
Fix Portal UI Bug

### PR DESCRIPTION
**Pull request by marvinbuss**
## Summary of the Pull Request
This PR fixes a bug in the Portal UI that is caused because of a change in the Portal UI Framework.

## References
The current Portal UI reports that a UI Element cannot be loaded.

## PR Checklist
* [x] Closes Issue https://github.com/Azure/data-landing-zone/issues/225
* [x] Code of Conduct signed. If not, go to [Code of Conduct](https://github.com/Azure/data-management-zone/blob/main/CODE_OF_CONDUCT.md).

## Validation Steps Performed
See below

### CODE REVIEW

**Comment by marvinbuss** [comment]
AIO Deployment
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Ffix_ui%2Fdocs%2Freference%2FdataManagementAnalytics.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Ffix_ui%2Fdocs%2Freference%2Fportal.dataManagementAnalytics.json)

Data Management Zone
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Ffix_ui%2Finfra%2Fmain.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Ffix_ui%2Fdocs%2Freference%2Fportal.dataManagementZone.json)

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by esbran — APPROVED** [review]
Looks awesome

**Pull request merged**
