### PR TITLE
Updated to Win11 and Updated AIO Deployment Parameters

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
Updated Input Parameters and Options for Deployment including parameters that were removed and added due to other PRs.
We are also switching to Windows 11 Enterprise as an option for the Bastion Host Deployment.

### CODE REVIEW

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by marvinbuss** [comment]
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Faio_parameter_updates%2Fdocs%2Freference%2FenterpriseScaleAnalytics.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Faio_parameter_updates%2Fdocs%2Freference%2Fportal.enterpriseScaleAnalytics.json)

**Comment by mariekekortsmit** [comment]
Awesome, thanks Marvin!

**Review by amanjeetsingh — COMMENTED** [review]
LGTM

**Review by amanjeetsingh — APPROVED** [review]

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Pull request merged**
