### PR TITLE
Updated Key Vault

### PR DESCRIPTION
**Pull request by marvinbuss**
## Summary of the Pull Request
* Disable public network access on Key Vault

## References
No references

## PR Checklist
* [x] Closes Issue #xxx
* [x] Code of Conduct signed. If not, go to [Code of Conduct](https://github.com/Azure/data-management-zone/blob/main/CODE_OF_CONDUCT.md).

## Validation Steps Performed
See automated checks

### CODE REVIEW

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by mikeleuer** [comment]
Can this get merged? 
LGTM

**Review by mikeleuer — APPROVED** [review]

**Comment by marvinbuss** [comment]
Closing because of https://github.com/Azure/data-management-zone/pull/311

**Pull request closed without merging**
