### PR TITLE
Improving Region Availability

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
Improving Region Availability for DMA by including the list of regions where Premium Firewall is available.
Also updating the Purview list. Also removed unnecessary dependency based on linting rules.

### CODE REVIEW

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by marvinbuss** [comment]
AIO Deployment
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Flocation_improvements%2Fdocs%2Freference%2FdataManagementAnalytics.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Flocation_improvements%2Fdocs%2Freference%2Fportal.dataManagementAnalytics.json)

Bastion Deployment
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Flocation_improvements%2Fdocs%2Freference%2Fbastionhost%2Fmain.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Flocation_improvements%2Fdocs%2Freference%2Fbastionhost%2Fportal.json)

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by amanjeetsingh — DISMISSED** [review]

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by esbran — APPROVED** [review]
Looks good

**Pull request merged**
