### PR TITLE
New Network Capabilities

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
Following features will be added by this PR:
*  Conditional Azure Firewall Subnet Deployment: Removes the deployment of the Azure Firewall Subnet in case the customer does not want to deploy Private DNS Zones and Azure Firewall in their Data Management Zone. 
* Adds flexibility to change the Firewall SKU to standard for cost savings in the DMZ.

### CODE REVIEW

**Comment by marvinbuss** [comment]
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Fconditional_subnets%2Fdocs%2Freference%2FenterpriseScaleAnalytics.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Fconditional_subnets%2Fdocs%2Freference%2Fportal.enterpriseScaleAnalytics.json)

**Review by amanjeetsingh — DISMISSED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by amanjeetsingh — APPROVED** [review]

**Review by amanjeetsingh — APPROVED** [review]

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Review by amanjeetsingh — DISMISSED** [review]

**Review by sasever — CHANGES_REQUESTED** [review]
Does not deploy due to network.bicep having hardcoded premium feature for firewall policy resource : intrusionDetection (line#205).  In case of standard firewall selection this option can not be used since it is a premium feature as listed here https://docs.microsoft.com/en-us/azure/firewall/premium-features.
tested this by changing the deployment URL to: https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Fconditional_subnets%2Finfra%2Fmain.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Fconditional_subnets%2Fdocs%2Freference%2Fportal.dataManagementZone.json

From the UI the selection  menu appeared for standard and premium and when standard selected deployment failed with below error on step network services: 
`
{
    "status": "Failed",
    "error": {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
        "details": [
            {
                "code": "BadRequest",
                "message": "{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"FirewallPolicyPremiumOnlyProperties\",\r\n    \"message\": \"Firewall Policy 757c4165-0823-49f7-9678-5a85fe5e17cc contains premium only properties - Intruston Detection\"\r\n  }\r\n}"
            }
        ]
    }
} `

**Comment by marvinbuss** [comment]
Thanks @sasever. Let me fix this quickly.

**Comment by marvinbuss** [comment]
Hi @sasever,
Can you please test this again?

**Review by sasever — CHANGES_REQUESTED** [review]
Tested with the same URL, still throws the same error:
{
    "status": "Failed",
    "error": {
        "code": "FirewallPolicyPremiumOnlyProperties",
        "message": "Firewall Policy 757c4165-0823-49f7-9678-5a85fe5e17cc contains premium only properties - Intruston Detection"
    }
}

**Review by marvinbuss — COMMENTED** [review]
LGTM!
Sorry @sasever, I forgot to check in the new ARM template. If you don't mind testing it now? My mistake.

**Review by sasever — APPROVED** [review]
Also tested the deployment for both premium and standard flows with successful deployment.
Good to Go.

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Pull request merged**
