### PR TITLE
Fix All-in-one Template Bug

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
Fix validation Issue in all-in-one template.

### CODE REVIEW

**Comment by marvinbuss** [comment]
AIO Deployment
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Fbugfix%2Fdocs%2Freference%2FenterpriseScaleAnalytics.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Fbugfix%2Fdocs%2Freference%2Fportal.enterpriseScaleAnalytics.json)

Bastion Deployment
[Preview Link](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Fbugfix%2Fdocs%2Freference%2Fbastionhost%2Fmain.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fdata-management-zone%2Fmarvinbuss%2Fbugfix%2Fdocs%2Freference%2Fbastionhost%2Fportal.json)

**Comment by marvinbuss** [comment]
This PR makes the validation pass again:
image

**Comment by marvinbuss** [comment]
Full deployment worked successfully:
image

**Review by esbran — APPROVED** [review]

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Pull request merged**
