### PR TITLE
Updated Purview Studio DNS Setup

### PR DESCRIPTION
**Pull request by marvinbuss**
**This PR fixes**
This PR updates the DNS setup for Purview. The Purview team recently has made some changes to the Private Endpoints and DNS setup, which is fixed by this PR. More details can be found in the referenced issue report.

### CODE REVIEW

**Comment by marvinbuss** [comment]
This is how the new setup looks like for the Portal PE for Purview:
image

@zeinab-mk Please take a brief look.

**Review by marvinbuss — COMMENTED** [review]
LGTM!

**Comment by marvinbuss** [comment]
> This is how the new setup looks like for the Portal PE for Purview:
> image
> 
> @zeinab-mk Please take a brief look.

Got her response and she said that it looks as expected.

**Comment by amanjeetsingh** [comment]
Good to go.

**Review by amanjeetsingh — APPROVED** [review]
LGTM!

**Pull request merged**
